### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by MohanKrishnaKadappu**

### CODE REVIEW

**Review by hugovk — CHANGES_REQUESTED** [review]
@MohanKrishnaKadappu  Please do not create spam PRs for Hacktoberfest, it's against the rules and values, and not fair on other maintainers.

https://hacktoberfest.digitalocean.com/

Maintainers: Please apply an `invalid` label to this PR so it doesn't count to Hacktoberfest.

**Comment by MohanKrishnaKadappu** [comment]
> @MohanKrishnaKadappu Please do not create spam PRs for Hacktoberfest, it's against the rules and values, and not fair on other maintainers.
> 
> https://hacktoberfest.digitalocean.com/
> 
> Maintainers: Please apply an `invalid` label to this PR so it doesn't count to Hacktoberfest.

It was just by mistake!!...will contribute on real project tq ..

**Comment by hugovk** [comment]
@MohanKrishnaKadappu You can start by closing this spam PR.

**Comment by MohanKrishnaKadappu** [comment]
Closed

**Pull request closed without merging**
