### PR TITLE
Changes for openSUSE official packages

### PR DESCRIPTION
**Pull request by vinzv**

### CODE REVIEW

**Comment by strycore** [comment]
So Lutris is officially in the SUSE repos? uh, who would have known! :thinking: 
I'm ok with merging that and deploying it because if Lutris isn't available in the repos *then*, I might have a *slight* chance of hearing back from some SUSE users.

**Comment by strycore** [comment]
And if Lutris is really in the official repos then that's even better news since we're not tied to OBS anymore.

**Comment by Mirppc** [comment]
i dont trust this commit.  i will continue using the non-opensuse provided version of Lutris from Strycore. 

 @vinzv if you really are going to do the work to keep Lutris maintained for SUSE and Opensuse i am always available on the #suse irc channel and in the Opensuse discord server.  Also try joining the Lutris irc channel and or their discord channel to be active and a bit more communicative.

**Comment by strycore** [comment]
I have deployed this commit in hope of getting some kind of communication going with the official Lutris SUSE maintainers. 
Everything about the inclusion of Lutris in the official SUSE repos has been very secretive. I have no I idea who is in charge (and I certainly wasn't aware that the package had landed in the repos)

**Comment by vinzv** [comment]
@Mirppc So for changing a repo URL to the official one I need to idle on your IRC chan? Oh come on. Read the commit messages. No need to trust me. The official packages are built by Dominique Leuenberger, TW release manager.

@strycore I was surprised as well. Dimstar is available via email, mostly on opensuse-factory mailing list. I can help with getting in touch.

**Comment by tannisroot** [comment]
Just want to note that Lutris may not work correctly on OpenSUSE since it defaults to BTRFS.
It might be a good idea to backport this for the OpenSUSE package https://github.com/lutris/lutris/pull/1421

**Comment by Mirppc** [comment]
@tannisroot it works fine on btrfs.  I have lutris running on a laptop with btrfs enabled but i am using @strycore 's repo.

@vinzv the reason for the irc is to be in communication with the devs so that fixes can be made much faster and easier.  Boomatower of packman was one of the people who helped with this.  Having and active maintainer available for when someone has a suse specific issue will benefit both lutris and opensuse.

**Comment by strycore** [comment]
@vinzv thanks a lot! I have contacts for pretty much every distro maintainers out there but I was left clueless when it came to SUSE!
I just need to know how will updates be handled when I push releases and if packages will be built for all supported SUSE versions.

**Comment by strycore** [comment]
@tannisroot that is not strictly related to SUSE, plus the fix should be out in a couple of weeks

**Pull request merged**
