### PR TITLE
Change the home page game banners order hourly

### PR DESCRIPTION
**Pull request by michaelbutler**
I personally thought it was odd always seeing the Overwatch banner first whenever I visited Lutris.net. I thought that maybe it would give a fresh look to change the banner ordering randomly on an hourly basis (but for a whole hour it will stay in that order) to give these other "top-tier" games a chance. Tested it with the local dev environment and it worked fine.

Screenshot from 2020-09-28 10-33-31

Also fixed a typo, and moved a `<style>` block into the `<head>` to be more HTML compliant.

What do you think?

### CODE REVIEW

**Comment by AlexanderRavenheart** [comment]
I would suggest waiting until the Bootstrap 4 refresh is complete (see bs4-refresh branch if you want to help make it a reality sooner) before rebasing this (if it would still be something desired) as to avoid creating unnecessary conflicts.

**Comment by michaelbutler** [comment]
@AlexanderRavenheart sounds good, I'll take a look at the bootstrap 4 refresh. Will the django app still be serving HTML responses? or is it switching to a full javascript front end with django just returning JSON API responses?

**Comment by AlexanderRavenheart** [comment]
HTML and Ajax based HTML snippets for now. A full rework to a Application based front-end is way too much work. I started the upgrade to BS4 to modernize the codebase and ease development.

**Comment by strycore** [comment]
we no longer have a carousel on the homepage so this no longer needed

**Pull request closed without merging**
