### PR TITLE
Issue 45: Auto-installer should be hidden if there's a (published) manual installer for the same platform

### LINKED ISSUE #45: Auto-installer should be hidden if there's a (published)  manual installer for the same platform

### PR DESCRIPTION
**Pull request by MichaelRupertDev**
Should fix #45

### CODE REVIEW

**Comment by strycore** [comment]
@charlydelta see the comment I made above, this is not the desired behavior as it would mask all auto-installers if manually created ones exist. Say that you have a game for MS-DOS and Super Nintendo, once an installer for the DOS version is created, this would mask the Super Nintendo one. The Super Nintendo auto-installer should only be masked if there's a manually created installer for the Super Nintendo.

**Comment by charlydelta** [comment]
> see the comment I made above

Weird, I don't see any comment. However, you're right, I wasn't thinking about that.

**Comment by strycore** [comment]
@charlydelta yes, I forgot to actually publish the review ^^

**Comment by charlydelta** [comment]
I think we can safely declare this MR as stale and close it. As you said, the fix is not as trivial as it seems and we need to go deeper. We still have #45 for reference.

**Comment by strycore** [comment]
I agree, this can be closed.

**Pull request closed without merging**
